openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
description: API for the AI-powered RAG chatbot for the Physical AI & Humanoid Robotics Textbook.

servers:
  - url: https://api.textbook.example.com/v1

paths:
  /query:
    post:
      summary: Query the RAG Chatbot
      description: Submits a natural language query to the chatbot and receives a relevant response based on textbook content.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The natural language question from the user.
                  example: "What is ROS 2?"
                user_id:
                  type: string
                  description: Optional user ID for personalization or logging.
                  example: "user123"
                context_chapter_slug:
                  type: string
                  description: Optional slug of the current chapter for contextualized queries.
                  example: "ros2-fundamentals"
      responses:
        '200':
          description: Successful response with the chatbot's answer.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The answer generated by the chatbot.
                    example: "ROS 2 (Robot Operating System 2) is a flexible framework for writing robot software..."
                  sources:
                    type: array
                    description: List of document chunks from which the answer was derived.
                    items:
                      type: object
                      properties:
                        chunk_id:
                          type: string
                        chapter_slug:
                          type: string
                        subchapter_slug:
                          type: string
        '400':
          description: Invalid request payload.
        '500':
          description: Internal server error.

  /health:
    get:
      summary: Health Check
      description: Checks the health and status of the RAG chatbot service.
      responses:
        '200':
          description: Service is healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
